// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1SthxA1cIMlVn4UzNX3OiXEw0AtxTKC0',
    appId: '1:710329249990:web:37b9bb8e7c8e534e05a7c7',
    messagingSenderId: '710329249990',
    projectId: 'serdah2-fcb04',
    authDomain: 'serdah2-fcb04.firebaseapp.com',
    databaseURL: 'https://serdah2-fcb04-default-rtdb.firebaseio.com',
    storageBucket: 'serdah2-fcb04.appspot.com',
    measurementId: 'G-2L00L729YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfDDAUDD_nWoeM5rbri0v5RjowCZzYbc',
    appId: '1:710329249990:android:42403b9368e1aaef05a7c7',
    messagingSenderId: '710329249990',
    projectId: 'serdah2-fcb04',
    databaseURL: 'https://serdah2-fcb04-default-rtdb.firebaseio.com',
    storageBucket: 'serdah2-fcb04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7lXeou3_ZOYVvkhHsPgZTouo-N1pWBw',
    appId: '1:710329249990:ios:ddf953caf2cd8cd705a7c7',
    messagingSenderId: '710329249990',
    projectId: 'serdah2-fcb04',
    databaseURL: 'https://serdah2-fcb04-default-rtdb.firebaseio.com',
    storageBucket: 'serdah2-fcb04.appspot.com',
    iosBundleId: 'com.example.mid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7lXeou3_ZOYVvkhHsPgZTouo-N1pWBw',
    appId: '1:710329249990:ios:778d07ac8637052805a7c7',
    messagingSenderId: '710329249990',
    projectId: 'serdah2-fcb04',
    databaseURL: 'https://serdah2-fcb04-default-rtdb.firebaseio.com',
    storageBucket: 'serdah2-fcb04.appspot.com',
    iosBundleId: 'com.example.mid.RunnerTests',
  );
}
